version: '3'
services:
  vprodb:
    images: harishdevops07/vprofiledb:v1
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata: /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

  vprocache01:
    images: memcached
    ports:
      - "11211:11211"

  vpromq01:
    images: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproapp:
    images: harishdevops07/vprofileapp:v1
    ports:
      - "8080:8080"
    volumes:
      - vproappdata: /usr/local/tomcat/webapps

  vproweb:
    images: harishdevops07/vprofileweb:v1
    ports:
      - "80:80"
volumes:
  vprodbdata: {}
  vproappdata: {}

